/* ============================================================
   PAWBIN PRODUCT DATA — single source of truth for product pages
   Ratings/reviews are deliberately varied and realistic.
   ============================================================ */
window.PAWBIN_PRODUCTS = {
/* ---------------- DOGS ---------------- */
'kong-classic':{name:'KONG Classic Chew Toy (M)',species:'dog',price:1199,img:'dog-kong-classic',tags:['chew','tough','enrichment'],rating:4.8,count:1243,
 blurb:'The red rubber benchmark for power chewers. Bounces unpredictably, stuffs with treats, and outlasts almost everything we\'ve tested.',
 details:['Natural KONG rubber flexes under heavy jaws instead of cracking, and the hollow core takes peanut butter, wet food or our own treat paste. Freezing it turns a ten-minute toy into a forty-minute one.','In our four-week trial it was the only toy all six tester power chewers failed to destroy. It does smell faintly of rubber for the first day or two — air it out before giving it to a sniffy dog.'],
 specs:[['Material','Natural KONG rubber'],['Size','M — 9 cm · dogs 7–16 kg'],['Chew rating','5/5'],['Cleaning','Top-rack dishwasher safe']],
 reviews:[
  {n:'Gareth H.',loc:'Wrexham',d:'2026-08-19',r:5,v:1,h:41,t:'Third one we\'ve bought as the pups grow. Our staffy has destroyed every "indestructible" toy on the market; this one\'s still here after eight months.'},
  {n:'Aisha K.',loc:'Bradford',d:'2026-07-30',r:4,v:1,h:17,t:'Does the job for our lurcher. Only grumble is the rubber smell when it first arrived — took a couple of days on the balcony to air out.'},
  {n:'Tom W.',loc:'Sheffield',d:'2026-06-11',r:5,v:0,h:9,t:'Bounces like madness, dog loves it. Frozen with peanut butter it buys me a full hour of peace on work calls.'}]},
'chuckit-launcher':{name:'Chuckit! Ball Launcher 26M',species:'dog',price:1499,img:'dog-chuckit-launcher',tags:['fetch','exercise'],rating:4.7,count:861,
 blurb:'Doubles your throwing distance and never touches slobbery balls. The 26M is the sweet spot for parks and beaches.',
 details:['The plastic arm flexes on release so even a lazy wrist flings a ball 30+ metres. The grip picks the ball straight off the ground — no more bending into the mud.','We\'d love a slightly softer grip foam for wet winters, hence not a perfect score from our wristy tester. Still the single best value fetch upgrade there is.'],
 specs:[['Length','26M (66 cm)'],['Fits','Chuckit! medium balls, tennis balls'],['Chew rating','n/a — it\'s a thrower'],['Cleaning','Rinse and dry']],
 reviews:[
  {n:'Fiona M.',loc:'Edinburgh',d:'2026-09-01',r:5,v:1,h:33,t:'Border collie, zero arms on my part after a shoulder op. This thing has saved us both. She comes back tired for the first time in her life.'},
  {n:'Dev P.',loc:'Leicester',d:'2026-07-14',r:4,v:1,h:12,t:'Works exactly as advertised. Grip foam goes a bit slimy in the rain so I wipe it down — one star\'s worth of faff.'},
  {n:'Sandra B.',loc:'York',d:'2026-05-02',r:5,v:1,h:8,t:'Bought for the granddog, kept it for the dog. Lightweight enough that my mum (78) can use it.'}]},
'snuffle-mat':{name:'Snuffle Feeder Mat',species:'dog',price:1899,img:'dog-snuffle-mat',tags:['enrichment','calming','feeding'],rating:4.6,count:2210,
 blurb:'Our #1 seller. A fleece foraging mat that turns dinner into 15 quiet minutes of nose work.',
 details:['Hundreds of fleece strips hide kibble or treats; the non-slip base stays put on laminate. It\'s the fastest way we know to settle a dog that inhales its food.','Machine washes at 30° and has survived 40+ washes in our tester households. Heavy droolers will soak it — expect to wash weekly, not monthly.'],
 specs:[['Size','50 × 50 cm'],['Base','Non-slip oxford cloth'],['Chew rating','2/5 — supervised for shredders'],['Cleaning','Machine wash 30°']],
 reviews:[
  {n:'Priya N.',loc:'Manchester',d:'2026-08-27',r:5,v:1,h:58,t:'The only reason our spaniel sits still before dinner. Three months of daily use, still in one piece.'},
  {n:'Colin R.',loc:'Hull',d:'2026-07-08',r:4,v:1,h:21,t:'Does what it says. Our lab figured out she can just tip it upside down, so we hold an edge. Docked a star for that design oversight.'},
  {n:'Megan L.',loc:'Cardiff',d:'2026-06-20',r:3,v:1,h:14,t:'Good mat but smaller than I expected for a big dog — should have sized up. My fault really, measure first.'}]},
'brick-puzzle':{name:'Treat Brick Puzzle',species:'dog',price:2299,img:'dog-brick-puzzle',tags:['puzzle','enrichment'],rating:4.5,count:534,
 blurb:'A sliding-brick puzzle for dogs that have graduated from beginner feeders. Three move types keep most dogs thinking for 20 minutes.',
 details:['Red bricks slide, white bones flip, and the combo moves need a paw-then-nose sequence. Non-slip feet keep the board honest on hard floors.','Clever dogs will learn the pattern in a week — rotate it with another toy to keep it fresh. Not for dogs that eat plastic: the bricks are sturdy but not chew-proof.'],
 specs:[['Size','38 × 25 cm'],['Level','Intermediate'],['Chew rating','2/5 — it\'s a thinker, not a chewer'],['Cleaning','Wipe or hand wash']],
 reviews:[
  {n:'Hannah S.',loc:'Bristol',d:'2026-08-05',r:5,v:1,h:26,t:'Our collie solved a "hard" puzzle app in days but this one still slows her down. Rainy day saviour.'},
  {n:'Joe T.',loc:'Newcastle',d:'2026-06-28',r:4,v:1,h:11,t:'Solid build, dog engaged. She cracked the sequence in about a week so now we shuffle which compartments get treats.'},
  {n:'Rita D.',loc:'Luton',d:'2026-05-19',r:3,v:0,h:7,t:'Good quality but my beagle only cares about flipping the bones and ignores the sliders. Depends on your dog, I suppose.'}]},
'rope-tug':{name:'Knotted Cotton Rope Tug',species:'dog',price:899,img:'dog-rope-tug',tags:['tug','dental','tough'],rating:4.4,count:1876,
 blurb:'A proper knotted cotton tug for the price of a coffee. Flosses teeth while you play.',
 details:['Tight-knotted undyed cotton, no plastic core to splinter. The knots give a satisfying give-and-take for terriers up to labs.','It frays. That\'s what ropes do, and it\'s half the fun — but if your dog eats the fluff rather than spitting it, supervise or size up to the tiger plush instead.'],
 specs:[['Length','45 cm'],['Material','Undyed cotton rope'],['Chew rating','3/5'],['Cleaning','Machine wash 30°']],
 reviews:[
  {n:'Big Dave',loc:'Stoke',d:'2026-09-10',r:5,v:1,h:19,t:'Groomer recommended for my nervous rescue. Tug war every evening, she\'s a different dog. For £9 it\'s a steal.'},
  {n:'Emma J.',loc:'Norwich',d:'2026-07-22',r:4,v:1,h:10,t:'Lasted six weeks of daily tug with a springer before the end knot gave way. About right for a rope, would buy again.'},
  {n:'Kev O.',loc:'Birkenhead',d:'2026-06-03',r:2,v:1,h:15,t:'My staffy had it in shreds in a weekend and ate half the fluff. Fine for gentle players, not for mine. Returns process was smooth at least.'}]},
'wobbler-ball':{name:'Wobbler Treat Ball',species:'dog',price:1399,img:'dog-wobbler-ball',tags:['enrichment','feeding','puzzle'],rating:4.3,count:742,
 blurb:'A wobble-and-tip treat dispenser that rewards batting without ever bouncing under the sofa.',
 details:['Weighted base keeps it upright; kibble spills from the top hole as it wobbles. Great for dogs that find sliding puzzles frustrating.','The hole size suits standard kibble — big-breed kibble jams, so check your size. Loud-ish on laminate; a rug solves it.'],
 specs:[['Height','17 cm'],['Hole','Fits kibble up to 12 mm'],['Chew rating','3/5'],['Cleaning','Twists apart, hand wash']],
 reviews:[
  {n:'Lesley F.',loc:'Dundee',d:'2026-08-14',r:5,v:1,h:22,t:'Two dachshunds, one wobbler, total silence for twenty minutes. It clicks on our laminate so it lives on the hall rug.'},
  {n:'Marco V.',loc:'Peterborough',d:'2026-07-01',r:4,v:1,h:9,t:'Does the job for breakfast. Wish the hole were adjustable for larger kibble — ours jams if I overfill.'},
  {n:'Stacey G.',loc:'Swansea',d:'2026-05-27',r:3,v:1,h:6,t:'Clever toy but my dog lost interest once she realised it doesn\'t bounce. More exciting for food-motivated dogs than ball-motivated ones.'}]},
'smart-ball':{name:'Smart Rolling Ball (USB-C)',species:'dog',price:2699,img:'dog-smart-ball',tags:['tech','enrichment','fetch'],rating:4.2,count:418,
 blurb:'A motion-activated self-rolling ball for solo play days. Two-hour battery, USB-C, quiet enough for flats.',
 details:['Rolls in random patterns, pauses, and restarts when nudged — the randomness is what keeps dogs engaged. The rubber shell takes terrier teeth; we wouldn\'t trust it to a mastiff.','Battery is honest at ~2 hours of active rolling. It can get itself wedged under low sofas, which ends the game early — hence the realistic score.'],
 specs:[['Battery','2 h active · USB-C'],['Modes','3 speed patterns'],['Chew rating','3/5'],['Cleaning','Wipe clean']],
 reviews:[
  {n:'Natalie C.',loc:'London',d:'2026-08-23',r:5,v:1,h:17,t:'Flat life with a jack russell is hard; this buys us a walk\'s worth of energy indoors. She pounces on it like prey.'},
  {n:'Phil B.',loc:'Wigan',d:'2026-07-17',r:3,v:1,h:20,t:'Fun for about a week, then it spends half its life wedged under the settee and the dog barks at it to come out. Amusing but overpriced for that.'},
  {n:'Aisha R.',loc:'Oxford',d:'2026-06-09',r:4,v:1,h:8,t:'Quiet motor, decent battery, dog interested. Docked a star because the charging flap is fiddly.'}]},
'lick-mat':{name:'Lick Mat + Slow Feeder',species:'dog',price:1299,img:'dog-lick-mat',tags:['calming','feeding','bath-time'],rating:4.6,count:1509,
 blurb:'Suction-backed silicone lick mat for baths, nail trims and vet visits. Licking is self-soothing; this is 20 minutes of it.',
 details:['Flower-shaped nubs hold peanut butter, yoghurt or wet food; strong suction cups stick to bath tiles and fridge doors. Freezes solid for longer sessions.','Silicone is food-grade and dishwasher safe. Greasy spreads need a proper scrub — the texture that slows licking also slows washing.'],
 specs:[['Size','22 cm flower'],['Suction','4 cups, bath-tile tested'],['Chew rating','2/5'],['Cleaning','Dishwasher safe']],
 reviews:[
  {n:'Beth A.',loc:'Leeds',d:'2026-09-03',r:5,v:1,h:29,t:'Bath time went from wrestling to spa day. Sticks properly to the tiles, which the cheap one from the market never did.'},
  {n:'Owen H.',loc:'Belfast',d:'2026-07-25',r:4,v:1,h:12,t:'Great for nail trims. Peanut butter cleanup is a bit of a faff but that\'s physics, not the product.'},
  {n:'Diane W.',loc:'Cambridge',d:'2026-06-15',r:4,v:1,h:7,t:'Works as described. Suction fails on our textured shower wall but grips the bath and fridge fine.'}]},
'teething-set':{name:'Puppy Teething Set (7 pieces)',species:'dog',price:1599,img:'dog-teething-set',tags:['puppy','chew','dental'],rating:4.7,count:987,
 blurb:'Seven textures for sore puppy gums — soft rope, rubber rings, a plush duck and a frozen-safe chew.',
 details:['Rotating textures is the trick with teething: soft for sore days, ribbed for itchy days. The set covers 8 weeks to 6 months without buying a toy a week.','The plush duck will die first. Accept it. Everything else has survived every tester litter so far.'],
 specs:[['Pieces','7'],['Age','8 weeks – 6 months'],['Chew rating','2–4/5 across the set'],['Cleaning','Machine or dishwasher by piece']],
 reviews:[
  {n:'Rachel & Tim',loc:'Harrogate',d:'2026-08-30',r:5,v:1,h:36,t:'Cocker spaniel pup, 12 weeks. The frozen ring saved our furniture during a heatwave. Duck is already limbless but that was always going to happen.'},
  {n:'Sam K.',loc:'Coventry',d:'2026-07-11',r:5,v:1,h:14,t:'Vet nurse recommended we get "multiple textures" — this box is exactly that. Cheaper than buying them separately.'},
  {n:'Gordon M.',loc:'Inverness',d:'2026-05-24',r:4,v:1,h:8,t:'Good value set. Our pup ignored the star chew and loves the rope, so it\'s a lottery, but at this price who cares.'}]},
'frisbee':{name:'Soft Flyer Frisbee',species:'dog',price:1199,img:'dog-frisbee',tags:['fetch','exercise'],rating:4.5,count:655,
 blurb:'A soft rubber flyer that floats far and won\'t chip teeth on a mistimed catch.',
 details:['Flexible natural rubber flexes on impact instead of the dog\'s mouth doing so. The paw-print texture gives a grip for wet-hand launches.','Flies true in light wind; in a proper Scottish gale it sails like any disc. Not a chew toy — fetch only, or the edge gets teeth marks.'],
 specs:[['Size','23 cm'],['Material','Soft natural rubber'],['Chew rating','2/5 — fetch only'],['Cleaning','Rinse']],
 reviews:[
  {n:'Isla D.',loc:'Aberdeen',d:'2026-08-08',r:5,v:1,h:18,t:'Soft enough that I stopped wincing when she mistimes a catch. Flies straight, washes in the sink.'},
  {n:'Chris N.',loc:'Middlesbrough',d:'2026-06-26',r:4,v:1,h:9,t:'Good flyer, dog loves it. She has started puncturing the edge with her canines when she holds it, so it\'s a season toy not a forever toy.'},
  {n:'Paula E.',loc:'Shrewsbury',d:'2026-05-30',r:4,v:1,h:5,t:'Nice and light for our whippet. Wish it came in a second colour — the teal vanishes in long grass.'}]},
'plush-tiger':{name:'Tough Plush Tiger',species:'dog',price:1299,img:'dog-plush-tiger',tags:['plush','squeaker','tough'],rating:4.3,count:811,
 blurb:'A plush that fights back: double-lined body, reinforced seams, and a squeaker that actually survives.',
 details:['Two fabric layers with a ripstop liner mean most dogs get a proper plush experience without the 4pm stuffing funeral. Squeaker sits in a sealed pouch.','A determined destroyer will still win eventually — that\'s true of every plush ever made. This one just makes them work for it.'],
 specs:[['Length','30 cm'],['Lining','Ripstop double layer'],['Chew rating','3/5'],['Cleaning','Machine wash 30°']],
 reviews:[
  {n:'Wendy T.',loc:'Doncaster',d:'2026-08-21',r:5,v:1,h:24,t:'First plush to survive our german shepherd past a day. Three weeks in, squeaker still squeaks. Astonished.'},
  {n:'Aaron J.',loc:'Blackpool',d:'2026-07-04',r:4,v:1,h:10,t:'Lasted a fortnight against a staffy, which for us is a record. Seam held, no stuffing eaten.'},
  {n:'Kim S.',loc:'Brighton',d:'2026-05-16',r:2,v:1,h:13,t:'My malinois opened it in twenty minutes. Fine toy, wrong dog — the chew-rating chart on the site was honest, to be fair.'}]},
'plush-fox':{name:'No-Stuff Fox Plush',species:'dog',price:1099,img:'dog-plush-fox',tags:['plush','gentle'],rating:4.6,count:1104,
 blurb:'All the plush satisfaction, zero stuffing. The one our rescue-dog testers chose themselves.',
 details:['No stuffing means nothing to eviscerate and nothing to swallow — just a floppy, shake-able, sleep-with-able fox with a gentle squeaker.','It was the first toy our anxious rescue tester picked up voluntarily. The squeaker is quiet by design; if your dog wants loud, pick the tiger.'],
 specs:[['Length','28 cm'],['Stuffing','None'],['Chew rating','2/5'],['Cleaning','Machine wash 30°']],
 reviews:[
  {n:'Nala\'s human',loc:'Glasgow',d:'2026-09-06',r:5,v:1,h:47,t:'Rescue lurcher who flinched at squeakers for two years now sleeps with this fox every night. We\'ve replaced it twice — with the same one, not a random substitute.'},
  {n:'Jerry L.',loc:'Watford',d:'2026-07-19',r:4,v:1,h:11,t:'Floppy and washable and the dog drags it everywhere. Squeaker died after a month but the fox lives on.'},
  {n:'Michelle P.',loc:'Exeter',d:'2026-06-07',r:4,v:1,h:6,t:'Great for gentle players. Our beagle treats it like a rag and it\'s held up surprisingly well.'}]},
/* ---------------- CATS ---------------- */
'feather-wand':{name:'Feather Wand Teaser',species:'cat',price:899,img:'cat-feather-wand',tags:['teaser','exercise'],rating:4.7,count:1932,
 blurb:'Telescopic wand, proper striped feathers, and a string length that keeps claws off your hand.',
 details:['The telescopic rod packs to 40 cm and extends to 90; the feathers are the real-stripe kind cats track properly. Two spare lures clip into the handle.','End every session with a "catch" or some cats get frustrated — pair it with the crinkle kicker for the finish.'],
 specs:[['Length','40–90 cm telescopic'],['Lures','2 feather heads included'],['Chew rating','n/a — store after play'],['Cleaning','Replace lures as needed']],
 reviews:[
  {n:'Sofia R.',loc:'London',d:'2026-08-25',r:5,v:1,h:39,t:'Two indoor cats, one wand, evening zoomies solved. The spare lure clipping into the handle is a thoughtful touch.'},
  {n:'Baz C.',loc:'Sunderland',d:'2026-07-09',r:4,v:1,h:14,t:'Cat obsessed. String frayed after six weeks of nightly abuse; ordered another lure, cheap enough.'},
  {n:'Anne H.',loc:'Bath',d:'2026-05-21',r:5,v:1,h:8,t:'Our 14-year-old who ignores everything will do three laps for this. That\'s the whole review.'}]},
'circuit':{name:'Senses Ball Circuit',species:'cat',price:2199,img:'cat-circuit',tags:['puzzle','tech','solo'],rating:4.5,count:1287,
 blurb:'The S-shaped ball track that survives solo play. Peek-a-boo holes keep paws busy for hours.',
 details:['A ball trapped in a clear S-track: bats forever, never loses the ball under the sofa. The peak-a-boo holes give three angles of attack.','Sturdy enough to sit on (tested by an 8 kg maine coon). Keen hunters solve it fast; rotate with the tunnel to keep it interesting.'],
 specs:[['Length','60 cm S-track'],['Ball','1 illuminated ball included'],['Chew rating','n/a'],['Cleaning','Wipes apart']],
 reviews:[
  {n:'Derek F.',loc:'Portsmouth',d:'2026-08-17',r:5,v:1,h:25,t:'Bought for one cat, both use it. It\'s the only toy that survives being left out permanently.'},
  {n:'Lily M.',loc:'Nottingham',d:'2026-07-02',r:4,v:1,h:16,t:'Good quality, cat engaged for weeks. The light ball mode eats batteries a bit fast.'},
  {n:'Robert G.',loc:'Chester',d:'2026-05-25',r:3,v:1,h:9,t:'Well made but my cat worked out she can just sit at one end and pat it rhythmically. Effective, less exercise than hoped.'}]},
'tower-tracks':{name:'3-Tier Track Tower',species:'cat',price:1699,img:'cat-tower-tracks',tags:['puzzle','solo','kitten'],rating:4.4,count:1650,
 blurb:'Three levels of trapped balls. The classic for a reason — kittens lose their minds, adults lose their dignity.',
 details:['Stacked tracks with different ball colours per tier; the base is weighted so it doesn\'t walk across the floor mid-hunt.','Kittens love it most; adult cats enjoy it in bursts. If your cat is a tower-topper, the window perch is the better buy.'],
 specs:[['Height','25 cm, 3 tiers'],['Balls','3 (one per tier)'],['Chew rating','n/a'],['Cleaning','Unscrews for a wipe']],
 reviews:[
  {n:'Katie B.',loc:'Reading',d:'2026-08-11',r:5,v:1,h:21,t:'Kittens discovered it within a minute of the box opening. Still playing daily two months later.'},
  {n:'Ian W.',loc:'Huddersfield',d:'2026-06-24',r:4,v:1,h:10,t:'Sturdy, doesn\'t slide. Our adult cat gives it a ceremonial two pats and leaves it to the kitten, which I think is the intended demographic.'},
  {n:'Zoe Q.',loc:'Swindon',d:'2026-05-12',r:3,v:1,h:7,t:'Fun but the balls are loud on laminate at 5am. We put it on a mat. Consider placement carefully.'}]},
'tunnel':{name:'Collapsible Play Tunnel',species:'cat',price:1799,img:'cat-tunnel',tags:['hideout','exercise','kitten'],rating:4.6,count:1421,
 blurb:'Crinkle-fabric tunnel that folds flat when the humans need the floor back.',
 details:['The crinkle lining is the secret — cats hear their own movement amplified and go feral in the best way. Twists flat to 40 cm discs for storage.','Two-cat households report ambush games within the hour. The fabric is tougher than it looks; claw snags in six months of testing were cosmetic.'],
 specs:[['Length','90 cm, 3-way option available'],['Lining','Crinkle polyester'],['Chew rating','n/a'],['Cleaning','Wipe down']],
 reviews:[
  {n:'Farah A.',loc:'Birmingham',d:'2026-08-28',r:5,v:1,h:30,t:'Two cats, one tunnel, constant ambush warfare. Folds flat behind the sofa when we have guests. Best £18 in the house.'},
  {n:'Pete S.',loc:'Preston',d:'2026-07-15',r:4,v:1,h:12,t:'Crinkle sound is properly enticing. Cat dragged it across the kitchen repeatedly; no damage so far.'},
  {n:'Grace V.',loc:'Ipswich',d:'2026-06-02',r:4,v:1,h:5,t:'Kitten loves it, adult cat pretends not to care then uses it at 3am. We hear everything. Worth it.'}]},
'catnip-bananas':{name:'Catnip Bananas (4-pack)',species:'cat',price:799,img:'cat-catnip-bananas',tags:['catnip','gentle','kitten'],rating:4.5,count:2044,
 blurb:'Four felt bananas stuffed with decent-strength catnip. Cheap, washable, and reliably entertaining.',
 details:['Felt holds its shape better than plush and survives biting; the catnip is the potent stuff, not the dust. Rotate one banana at a time to keep the effect strong.','Store the spares in the included bag or every banana loses its magic in a week. You have been warned.'],
 specs:[['Pack','4 bananas'],['Fill','UK-grown catnip'],['Chew rating','1/5'],['Cleaning','Air dry']],
 reviews:[
  {n:'Mags D.',loc:'Liverpool',d:'2026-09-02',r:5,v:1,h:34,t:'Cat does the full routine — sniff, lick, bunny kick, nap. The rotation tip on the card actually works.'},
  {n:'Tariq H.',loc:'Slough',d:'2026-07-21',r:4,v:1,h:13,t:'Good nip strength. One of the four was dead on arrival smell-wise but support sent a replacement no fuss.'},
  {n:'Jenny K.',loc:'Derby',d:'2026-05-18',r:4,v:1,h:6,t:'Our cat is immune to cheap catnip but reacts to these, so the potency claim holds.'}]},
'laser-chaser':{name:'Automatic Laser Chaser',species:'cat',price:2499,img:'cat-laser-tower',tags:['tech','solo','exercise'],rating:4.2,count:377,
 blurb:'A random-pattern laser tower for solo hunt time. Auto-off after 15 minutes so nobody overdoes it.',
 details:['Projects unpredictable patterns at cat height; the 15-minute auto-off respects the "end the hunt" rule vets talk about. We recommend finishing with a physical toy and a treat.','Some cats find the motorised head fascinating in the wrong way and hunt the tower instead of the dot. Amusing, but not the point.'],
 specs:[['Runtime','15 min auto-off'],['Patterns','4 random'],['Power','3×AA included'],['Safety','Class 1 laser']],
 reviews:[
  {n:'Verity L.',loc:'Cheltenham',d:'2026-08-16',r:5,v:1,h:19,t:'Our testers\' cats queued for this one. Auto-off means I can leave it without guilt.'},
  {n:'Stu M.',loc:'Oldham',d:'2026-07-06',r:3,v:1,h:22,t:'Cat hunted the machine itself and had it in pieces in a fortnight. The dot was never the prey, apparently. Build is fine for gentler cats.'},
  {n:'Helen J.',loc:'Southampton',d:'2026-05-29',r:4,v:1,h:8,t:'Does exactly what it says. I follow the advice and end sessions with the kicker toy so she gets a "kill".'}]},
'mouse-toy':{name:'Motion-Sensor Mouse',species:'cat',price:1199,img:'cat-mouse-toy',tags:['tech','solo','teaser'],rating:4.3,count:509,
 blurb:'A plush mouse that twitches on its own when your cat stalks close. Motion sensor, feather tail, zero effort from you.',
 details:['The sensor wakes the mouse when paws approach, which sells the "alive" illusion better than constant movement. Feather tail gives a final-catch target.','Hard floors only — on carpet the twitching is muffled and cats lose interest faster.'],
 specs:[['Sensor','Motion-activated'],['Power','USB-C rechargeable'],['Chew rating','1/5'],['Cleaning','Wipe']],
 reviews:[
  {n:'Olive N.',loc:'Sheffield',d:'2026-08-20',r:5,v:1,h:16,t:'Kitchen floor + mouse = 20 minutes of stalking every morning. Recharge lasts us about a week.'},
  {n:'Gavin R.',loc:'Warrington',d:'2026-07-03',r:3,v:1,h:11,t:'Works, but on our carpet it barely moves and the cat clocks that quickly. Great on laminate, meh on rugs.'},
  {n:'Sue T.',loc:'Maidstone',d:'2026-05-22',r:4,v:1,h:5,t:'Cat was suspicious for a day, then obsessed. Battery door feels a bit flimsy hence four stars.'}]},
'cat-smart-ball':{name:'Smart Rolling Cat Ball (USB-C)',species:'cat',price:1999,img:'cat-smart-ball',tags:['tech','solo'],rating:4.4,count:623,
 blurb:'Self-driving LED ball that pauses, darts, and hides under nothing — quiet motor, quiet cat-appeal.',
 details:['Random dart-and-pause movement mimics prey better than constant rolling. The motor is genuinely quiet; our tester flats report no 3am complaints.','Shines on hard floors. Deep-pile carpet defeats it, like most things in life.'],
 specs:[['Battery','2 h · USB-C'],['Noise','<40 dB'],['Chew rating','2/5'],['Cleaning','Wipe']],
 reviews:[
  {n:'Amara O.',loc:'Manchester',d:'2026-08-24',r:5,v:1,h:14,t:'Quiet enough that it runs while I\'m on calls. Cat does the full ambush crouch routine daily.'},
  {n:'Neil B.',loc:'Kirkcaldy',d:'2026-07-12',r:4,v:1,h:9,t:'Good on our wood floors. Cat batted it under the sideboard once and sat waiting — which is arguably enrichment too.'},
  {n:'Carole F.',loc:'Guildford',d:'2026-06-05',r:3,v:1,h:7,t:'Mine watched it twice then decided it was beneath her. Younger cat loves it though. Cats gonna cat.'}]},
'window-perch':{name:'Window Perch Hammock',species:'cat',price:2699,img:'cat-window-perch',tags:['perch','calming'],rating:4.6,count:856,
 blurb:'Suction-cup window hammock rated to 20 kg. Cat TV, installed in two minutes.',
 details:['Four suction cups with twist-locks and a reinforced frame; our 8 kg maine coon tester sleeps on his daily. The fabric is a breathable mesh for summer.','Clean the glass properly first — suction fails on dust, not on product. Re-tighten the cups monthly.'],
 specs:[['Load','20 kg tested'],['Fixing','4 twist-lock suction cups'],['Chew rating','n/a'],['Cleaning','Fabric unzips, machine wash']],
 reviews:[
  {n:'Ruth E.',loc:'Harrogate',d:'2026-08-29',r:5,v:1,h:27,t:'Cat discovered birds within seconds. Has lived on it since. The twist-lock cups are the difference vs every other perch we\'ve tried.'},
  {n:'Alan P.',loc:'Crawley',d:'2026-07-16',r:4,v:1,h:12,t:'Holds our two (11 kg combined) fine. Needed a proper glass clean and a monthly re-tighten, as the card says.'},
  {n:'Donna M.',loc:'Lincoln',d:'2026-06-12',r:4,v:1,h:6,t:'Great perch. Our textured double glazing edge made one cup not sit flat, but three cups hold it level.'}]},
'sisal-post':{name:'Sisal Scratching Post',species:'cat',price:1999,img:'cat-sisal-post',tags:['scratch','stable'],rating:4.5,count:1178,
 blurb:'A 60 cm sisal post with a base that doesn\'t tip when a cat really commits.',
 details:['Tightly wound sisal rope on a weighted base — the wobble that puts cats off cheap posts is gone. Height suits full stretches for most cats.','If your cat prefers horizontal scratching, pair it with the kicker on the floor nearby.'],
 specs:[['Height','60 cm'],['Base','25 × 25 cm weighted'],['Wrap','Natural sisal rope'],['Cleaning','Vacuum']],
 reviews:[
  {n:'Faisal Y.',loc:'Bradford',d:'2026-08-13',r:5,v:1,h:20,t:'Sofa arms safe for the first time in two years. Base is properly heavy, no tipping even when he launches.'},
  {n:'Pam G.',loc:'Basildon',d:'2026-07-07',r:4,v:1,h:10,t:'Solid post, cat uses it daily. Sisal fluffs a little in the first week, normal apparently.'},
  {n:'Hugh D.',loc:'Truro',d:'2026-05-26',r:4,v:1,h:4,t:'Does the job. Our very tall bengal would benefit from a taller option — hint hint.'}]},
'kicker':{name:'Crinkle Kicker (2-pack)',species:'cat',price:999,img:'cat-kicker',tags:['catnip','teaser','gentle'],rating:4.6,count:1733,
 blurb:'Long crinkle-catnip kickers sized for proper bunny-kicking. Two-pack so one can be "the indoor one".',
 details:['The length matters: cats need something they can grab with front paws and rake with back legs. Crinkle core plus catnip covers both scent and sound hunters.','Machine washable, which no kicker we tested before this one managed to survive.'],
 specs:[['Pack','2 × 30 cm'],['Fill','Catnip + crinkle'],['Chew rating','1/5'],['Cleaning','Machine wash 30°']],
 reviews:[
  {n:'Bea S.',loc:'Oxford',d:'2026-08-26',r:5,v:1,h:23,t:'Full bunny-kick routine within minutes. Washed six times, still crinkles.'},
  {n:'Marcus J.',loc:'Romford',d:'2026-07-13',r:4,v:1,h:9,t:'Cat prefers this to toys costing triple. One star off because he now ignores the expensive ones entirely.'},
  {n:'Tina W.',loc:'Wakefield',d:'2026-05-31',r:4,v:1,h:5,t:'Good size for kicking. Catnip effect strong for the first fortnight then needs the rotation trick.'}]},
'cat-puzzle-feeder':{name:'Treat Puzzle Feeder',species:'cat',price:1599,img:'cat-puzzle-feeder',tags:['puzzle','feeding','enrichment'],rating:4.5,count:694,
 blurb:'A slow-feeder puzzle that makes cats work for dinner — the vet-approved answer to the 4am hunger yell.',
 details:['Cups and lids of varying difficulty; cats fish treats out with paws. Slows vacuum-eaters and bored cats alike.','Start with the easy cups only and add difficulty weekly. Greedy cats will attempt to tip the whole board — the base grips, mostly.'],
 specs:[['Size','25 × 20 cm'],['Difficulty','3 levels'],['Chew rating','n/a'],['Cleaning','Dishwasher top rack']],
 reviews:[
  {n:'Nadia B.',loc:'Leicester',d:'2026-08-18',r:5,v:1,h:18,t:'Two kittens eat breakfast at 6am instead of screaming at 4am. Genuinely life-changing.'},
  {n:'Oliver H.',loc:'Stockport',d:'2026-07-05',r:4,v:1,h:8,t:'Cat solved level one in a day, needed a week for the lids. Good progression curve.'},
  {n:'Janet C.',loc:'Norwich',d:'2026-05-20',r:4,v:1,h:6,t:'Solid plastic, washes fine. My cat flips the whole thing over if I underfill it, so fill generously.'}]},
/* ---------------- BUNDLES ---------------- */
'kitten-starter':{name:'Kitten Starter Kit',species:'bundle',price:3299,img:'cat-feather-wand',tags:['kitten','bundle'],rating:4.7,count:486,contains:['feather-wand','circuit','catnip-bananas'],
 blurb:'Wand, ball circuit and catnip bananas — the three things every new kitten actually uses, boxed.',
 details:['Everything in the box earned its place in four-week kitten-household trials: the wand for bonding play, the circuit for solo energy, the bananas for the first catnip introduction (wait until ~12 weeks).','Arrives with a chew-rating card and a two-minute "how to introduce each toy" guide.'],
 specs:[['Contents','3 toys'],['Age','8 weeks +'],['Box','Recyclable kraft']],
 reviews:[
  {n:'First-time cat dad',loc:'Bristol',d:'2026-08-22',r:5,v:1,h:26,t:'Kitten arrived Friday, box arrived Saturday. By Sunday she was asleep in the circuit box itself. All three toys in rotation a month later.'},
  {n:'Sandra L.',loc:'Falkirk',d:'2026-07-18',r:5,v:1,h:11,t:'Bought for my daughter\'s kitten. The intro guide is genuinely useful, not filler.'},
  {n:'Mo F.',loc:'Luton',d:'2026-06-08',r:4,v:1,h:7,t:'Great value vs buying separately. Kitten ignored the bananas till about 14 weeks, as the card predicted. Should have trusted the card.'}]},
'puppy-survival':{name:'New Puppy Survival Kit',species:'bundle',price:4499,img:'dog-teething-set',tags:['puppy','bundle'],rating:4.8,count:712,contains:['teething-set','rope-tug','chuckit-launcher','lick-mat'],
 blurb:'Teething set, rope tug, launcher and lick mat — the first eight weeks of puppy life, covered.',
 details:['The four tools that survived our tester litters: textures for teething, tug for bonding and rules, the launcher for tireless fetch days, and the lick mat for bath-time truces.','Comes with the same chew-rating card and a "week by week" introduction timeline.'],
 specs:[['Contents','4 items (7 pieces total)'],['Age','8 weeks +'],['Box','Recyclable kraft']],
 reviews:[
  {n:'Rachel & Tim',loc:'Harrogate',d:'2026-08-31',r:5,v:1,h:31,t:'Bought the kit instead of 20 random Amazon toys on panic. Right decision. The lick mat alone is worth it.'},
  {n:'Danny K.',loc:'Hull',d:'2026-07-20',r:5,v:1,h:14,t:'Cocker pup, 11 weeks. Everything in the box gets used weekly. The timeline card stopped us giving the puzzle stuff too early.'},
  {n:'Priya S.',loc:'Northampton',d:'2026-06-14',r:4,v:1,h:9,t:'Solid kit. Rope tug frayed fast with our heavy chewer, but that\'s ropes — the rest is going strong.'}]},
'rainy-day':{name:'Rainy Day Enrichment Box',species:'bundle',price:5499,img:'dog-snuffle-mat',tags:['bundle','enrichment'],rating:4.6,count:391,contains:['snuffle-mat','brick-puzzle','kicker','catnip-bananas'],
 blurb:'Snuffle mat, treat brick, kicker and bananas — a mixed cat-and-dog household\'s wet-weekend survival pack.',
 details:['Built for households with both species (or one of each energy). Dog gets the snuffle mat and brick; cat gets the kicker and bananas; everyone gets tired before 5pm.','The only multi-species bundle we sell — most enrichment boxes pretend you only own one type of animal.'],
 specs:[['Contents','4 toys'],['Species','Dogs + cats'],['Box','Recyclable kraft']],
 reviews:[
  {n:'The Hendersons',loc:'Cardiff',d:'2026-08-15',r:5,v:1,h:17,t:'Dog and cat both covered, which is rarer than it should be. Rainy bank holiday survived with all limbs attached.'},
  {n:'Aled W.',loc:'Bangor',d:'2026-07-01',r:4,v:1,h:8,t:'Good mix. Cat stole the snuffle mat once and the dog was furious, which I suppose is also enrichment.'},
  {n:'Jo P.',loc:'Salford',d:'2026-05-23',r:4,v:1,h:5,t:'Quality items, sensible combos. Would love a dog-only version of this box.'}]},
'chew-proof':{name:'Chew-Proof Big Dog Box',species:'bundle',price:5499,img:'dog-kong-classic',tags:['bundle','tough'],rating:4.7,count:358,contains:['kong-classic','smart-ball','rope-tug','frisbee'],
 blurb:'KONG, smart ball, rope tug and flyer — rated chew 3–5, for dogs that treat toys as a challenge.',
 details:['Every item is rated chew 3/5 or higher and survived our staffy and shepherd testers. The mix covers solo play, joint play and park play.','If your dog has a known plush addiction, this box is the intervention.'],
 specs:[['Contents','4 toys'],['Chew rating','3–5/5'],['Dog size','Medium +']],
 reviews:[
  {n:'Big Dave',loc:'Stoke',d:'2026-09-08',r:5,v:1,h:21,t:'Staffy approved. Nothing in the box died in week one, which has literally never happened before.'},
  {n:'Cheryl A.',loc:'Mansfield',d:'2026-07-26',r:5,v:1,h:10,t:'German shepherd, notorious destroyer. The KONG and flyer are daily fixtures two months in.'},
  {n:'Wayne B.',loc:'Grimsby',d:'2026-06-17',r:3,v:1,h:12,t:'Three of the four survived. He ate the rope tug in a weekend — my fault for leaving it out, per the chew chart, but worth knowing.'}]}
};
